const cardsData = [ 
   {
      id: 1,
      title: 'Капитанская дочка', 
      author: 'Александр Сергеевич Пушкин',
      description: 'История про честь и достоинство даже перед лицом смерти. Не зря эта история пользовалась популярностью у солдат во время Великой Отечественной войны...', 
   },
   {
      id: 2, 
      title: 'Хаджи-Мурат', 
      author: 'Лев Николаевич Толстой',
      description: '',
   },
   {
      id: 3, 
      title: 'Беглец', 
      author: 'Антон Павлович Чехов',
      description: 'Димас', 
   },
   {
      id: 4, 
      title: '', 
      author: 'Тютчев',
      description: '', 
   },
   {
      id: 5, 
      title: 'Детство', 
      author: 'Максим Горький',
      description: '',
   },
   {
      id: 6, 
      title: 'Борьба русского народа с немецкими интервентами в XII-XV вв.', 
      author: '',
      description: '', 
   },
   {
      id: 7, 
      title: 'Хаджи-Мурат', 
      author: 'Лев Николаевич Толстой',
      description: 'Володя', 
   },
   {
      id: 8, 
      title: 'Беглец', 
      author: 'Антон Павлович Чехов',
      description: '', 
   },
   {
      id: 9, 
      title: '', 
      author: 'Тютчев',
      description: '', 
   },
   {
      id: 10, 
      title: 'Детство', 
      author: 'Максим Горький',
      description: '', 
   },
   {
      id: 11, 
      title: 'Борьба русского народа с немецкими интервентами в XII-XV вв.', 
      author: '',
      description: '', 
   },
   {
      id: 12, 
      title: 'Капитанская дочка', 
      author: 'Александр Сергеевич Пушкин',
      description: '', 
   },
   {
      id: 13, 
      title: 'Хаджи-Мурат', 
      author: 'Лев Николаевич Толстой',
      description: 'Володя', 
   },
   {
      id: 14, 
      title: 'Беглец', 
      author: 'Антон Павлович Чехов',
      description: '', 
   },
   {
      id: 15, 
      title: '', 
      author: 'Тютчев',
      description: '', 
   },
   {
      id: 16, 
      title: 'Детство', 
      author: 'Максим Горький',
      description: '', 
   },
   {
      id: 17, 
      title: 'Борьба русского народа с немецкими интервентами в XII-XV вв.', 
      author: '',
      description: '', 
   },
   {
      id: 18, 
      title: 'Капитанская дочка', 
      author: 'Александр Сергеевич Пушкин',
      description: '', 
   },
   {
      id: 19, 
      title: 'Хаджи-Мурат', 
      author: 'Лев Николаевич Толстой',
      description: 'Володя', 
   },
   {
      id: 20, 
      title: 'Беглец', 
      author: 'Антон Павлович Чехов',
      description: '', 
   },
   {
      id: 21, 
      title: '', 
      author: 'Тютчев',
      description: '', 
   },
   {
      id: 22, 
      title: 'Детство', 
      author: 'Максим Горький',
      description: '', 
   },
   {
      id: 23, 
      title: 'Борьба русского народа с немецкими интервентами в XII-XV вв.', 
      author: '',
      description: '', 
   },
   {
      id: 24, 
      title: 'Капитанская дочка', 
      author: 'Александр Сергеевич Пушкин',
      description: '', 
   },
   {
      id: 25, 
      title: 'Хаджи-Мурат', 
      author: 'Лев Николаевич Толстой',
      description: 'Володя', 
   },
   {
      id: 26, 
      title: 'Беглец', 
      author: 'Антон Павлович Чехов',
      description: '', 
   },
   {
      id: 27, 
      title: '', 
      author: 'Тютчев',
      description: '', 
   },
   {
      id: 28, 
      title: 'Детство', 
      author: 'Максим Горький',
      description: '', 
   },
   {
      id: 29, 
      title: 'Борьба русского народа с немецкими интервентами в XII-XV вв.', 
      author: '',
      description: '', 
   },
   {
      id: 30, 
      title: 'Капитанская дочка', 
      author: 'Александр Сергеевич Пушкин',
      description: '', 
   },
   {
      id: 31, 
      title: 'Хаджи-Мурат', 
      author: 'Лев Николаевич Толстой',
      description: 'Володя', 
   },
   {
      id: 32, 
      title: 'Беглец', 
      author: 'Антон Павлович Чехов',
      description: '', 
   },
   {
      id: 33, 
      title: '', 
      author: 'Тютчев',
      description: '', 
   },
   {
      id: 34, 
      title: '', 
      author: 'Тютчев',
      description: '', 
   },
];