const cardsData = [ 
   {
      id: 1,
      title: 'Капитанская дочка', 
      author: 'Александр Сергеевич Пушкин',
      description: 'История про честь и достоинство даже перед лицом смерти. Не зря эта история пользовалась популярностью у солдат во время Великой Отечественной войны...',
      string: 'src="../image/books/1.jpg"', 
   },
   {
      id: 2, 
      title: 'Хаджи-Мурат', 
      author: 'Лев Николаевич Толстой',
      description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ex aspernatur inventore, enim accusantium a reprehenderit veritatis sint numquam necessitatibus expedita debitis. Beatae laboriosam officiis ipsum, aliquam neque delectus quas itaque.',
      string: 'src="../image/books/2.jpg"',
   },
   {
      id: 3, 
      title: 'Беглец', 
      author: 'Антон Павлович Чехов',
      description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ex aspernatur inventore, enim accusantium a reprehenderit veritatis sint numquam necessitatibus expedita debitis. Beatae laboriosam officiis ipsum, aliquam neque delectus quas itaque.',
      string: 'src="../image/books/3.jpg"', 
   },
   {
      id: 4, 
      title: '', 
      author: 'Тютчев',
      description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ex aspernatur inventore, enim accusantium a reprehenderit veritatis sint numquam necessitatibus expedita debitis. Beatae laboriosam officiis ipsum, aliquam neque delectus quas itaque.',
      string: 'src="../image/books/4.jpg"', 
   },
   {
      id: 5, 
      title: 'Детство', 
      author: 'Максим Горький',
      description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ex aspernatur inventore, enim accusantium a reprehenderit veritatis sint numquam necessitatibus expedita debitis. Beatae laboriosam officiis ipsum, aliquam neque delectus quas itaque.',
      string: 'src="../image/books/5.jpg"',
   },
   {
      id: 6, 
      title: 'Борьба русского народа с немецкими интервентами в XII-XV вв.', 
      author: '',
      description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ex aspernatur inventore, enim accusantium a reprehenderit veritatis sint numquam necessitatibus expedita debitis. Beatae laboriosam officiis ipsum, aliquam neque delectus quas itaque.',
      string: 'src="../image/books/6.jpg"', 
   },
   {
      id: 7, 
      title: 'Хаджи-Мурат', 
      author: 'Лев Николаевич Толстой',
      description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ex aspernatur inventore, enim accusantium a reprehenderit veritatis sint numquam necessitatibus expedita debitis. Beatae laboriosam officiis ipsum, aliquam neque delectus quas itaque.',
      string: 'src="../image/books/7.jpg"', 
   },
   {
      id: 8, 
      title: 'Беглец', 
      author: 'Антон Павлович Чехов',
      description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ex aspernatur inventore, enim accusantium a reprehenderit veritatis sint numquam necessitatibus expedita debitis. Beatae laboriosam officiis ipsum, aliquam neque delectus quas itaque.',
      string: 'src="../image/books/8.jpg"', 
   },
   {
      id: 9, 
      title: '', 
      author: 'Тютчев',
      description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ex aspernatur inventore, enim accusantium a reprehenderit veritatis sint numquam necessitatibus expedita debitis. Beatae laboriosam officiis ipsum, aliquam neque delectus quas itaque.',
      string: 'src="../image/books/9.jpg"', 
   },
   {
      id: 10, 
      title: 'Детство', 
      author: 'Максим Горький',
      description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ex aspernatur inventore, enim accusantium a reprehenderit veritatis sint numquam necessitatibus expedita debitis. Beatae laboriosam officiis ipsum, aliquam neque delectus quas itaque.',
      string: 'src="../image/books/10.jpg"', 
   },
   {
      id: 11, 
      title: 'Борьба русского народа с немецкими интервентами в XII-XV вв.', 
      author: '',
      description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ex aspernatur inventore, enim accusantium a reprehenderit veritatis sint numquam necessitatibus expedita debitis. Beatae laboriosam officiis ipsum, aliquam neque delectus quas itaque.',
      string: 'src="../image/books/11.jpg"', 
   },
   {
      id: 12, 
      title: 'Капитанская дочка', 
      author: 'Александр Сергеевич Пушкин',
      description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ex aspernatur inventore, enim accusantium a reprehenderit veritatis sint numquam necessitatibus expedita debitis. Beatae laboriosam officiis ipsum, aliquam neque delectus quas itaque.',
      string: 'src="../image/books/12.jpg"', 
   },
   {
      id: 13, 
      title: 'Хаджи-Мурат', 
      author: 'Лев Николаевич Толстой',
      description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ex aspernatur inventore, enim accusantium a reprehenderit veritatis sint numquam necessitatibus expedita debitis. Beatae laboriosam officiis ipsum, aliquam neque delectus quas itaque.',
      string: 'src="../image/books/13.jpg"', 
   },
   {
      id: 14, 
      title: 'Беглец', 
      author: 'Антон Павлович Чехов',
      description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ex aspernatur inventore, enim accusantium a reprehenderit veritatis sint numquam necessitatibus expedita debitis. Beatae laboriosam officiis ipsum, aliquam neque delectus quas itaque.',
      string: 'src="../image/books/14.jpg"', 
   },
   {
      id: 15, 
      title: '', 
      author: 'Тютчев',
      description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ex aspernatur inventore, enim accusantium a reprehenderit veritatis sint numquam necessitatibus expedita debitis. Beatae laboriosam officiis ipsum, aliquam neque delectus quas itaque.',
      string: 'src="../image/books/15.jpg"', 
   },
   {
      id: 16, 
      title: 'Детство', 
      author: 'Максим Горький',
      description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ex aspernatur inventore, enim accusantium a reprehenderit veritatis sint numquam necessitatibus expedita debitis. Beatae laboriosam officiis ipsum, aliquam neque delectus quas itaque.',
      string: 'src="../image/books/16.jpg"', 
   },
   {
      id: 17, 
      title: 'Борьба русского народа с немецкими интервентами в XII-XV вв.', 
      author: '',
      description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ex aspernatur inventore, enim accusantium a reprehenderit veritatis sint numquam necessitatibus expedita debitis. Beatae laboriosam officiis ipsum, aliquam neque delectus quas itaque.',
      string: 'src="../image/books/17.jpg"', 
   },
   {
      id: 18, 
      title: 'Капитанская дочка', 
      author: 'Александр Сергеевич Пушкин',
      description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ex aspernatur inventore, enim accusantium a reprehenderit veritatis sint numquam necessitatibus expedita debitis. Beatae laboriosam officiis ipsum, aliquam neque delectus quas itaque.',
      string: 'src="../image/books/18.jpg"', 
   },
   {
      id: 19, 
      title: 'Хаджи-Мурат', 
      author: 'Лев Николаевич Толстой',
      description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ex aspernatur inventore, enim accusantium a reprehenderit veritatis sint numquam necessitatibus expedita debitis. Beatae laboriosam officiis ipsum, aliquam neque delectus quas itaque.',
      string: 'src="../image/books/19.jpg"', 
   },
   {
      id: 20, 
      title: 'Беглец', 
      author: 'Антон Павлович Чехов',
      description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ex aspernatur inventore, enim accusantium a reprehenderit veritatis sint numquam necessitatibus expedita debitis. Beatae laboriosam officiis ipsum, aliquam neque delectus quas itaque.',
      string: 'src="../image/books/20.jpg"', 
   },
   {
      id: 21, 
      title: '', 
      author: 'Тютчев',
      description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ex aspernatur inventore, enim accusantium a reprehenderit veritatis sint numquam necessitatibus expedita debitis. Beatae laboriosam officiis ipsum, aliquam neque delectus quas itaque.',
      string: 'src="../image/books/21.jpg"', 
   },
   {
      id: 22, 
      title: 'Детство', 
      author: 'Максим Горький',
      description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ex aspernatur inventore, enim accusantium a reprehenderit veritatis sint numquam necessitatibus expedita debitis. Beatae laboriosam officiis ipsum, aliquam neque delectus quas itaque.',
      string: 'src="../image/books/22.jpg"', 
   },
   {
      id: 23, 
      title: 'Борьба русского народа с немецкими интервентами в XII-XV вв.', 
      author: '',
      description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ex aspernatur inventore, enim accusantium a reprehenderit veritatis sint numquam necessitatibus expedita debitis. Beatae laboriosam officiis ipsum, aliquam neque delectus quas itaque.',
      string: 'src="../image/books/23.jpg"', 
   },
   {
      id: 24, 
      title: 'Капитанская дочка', 
      author: 'Александр Сергеевич Пушкин',
      description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ex aspernatur inventore, enim accusantium a reprehenderit veritatis sint numquam necessitatibus expedita debitis. Beatae laboriosam officiis ipsum, aliquam neque delectus quas itaque.',
      string: 'src="../image/books/24.jpg"', 
   },
   {
      id: 25, 
      title: 'Хаджи-Мурат', 
      author: 'Лев Николаевич Толстой',
      description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ex aspernatur inventore, enim accusantium a reprehenderit veritatis sint numquam necessitatibus expedita debitis. Beatae laboriosam officiis ipsum, aliquam neque delectus quas itaque.',
      string: 'src="../image/books/25.jpg"', 
   },
   {
      id: 26, 
      title: 'Беглец', 
      author: 'Антон Павлович Чехов',
      description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ex aspernatur inventore, enim accusantium a reprehenderit veritatis sint numquam necessitatibus expedita debitis. Beatae laboriosam officiis ipsum, aliquam neque delectus quas itaque.',
      string: 'src="../image/books/26.jpg"', 
   },
   {
      id: 27, 
      title: '', 
      author: 'Тютчев',
      description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ex aspernatur inventore, enim accusantium a reprehenderit veritatis sint numquam necessitatibus expedita debitis. Beatae laboriosam officiis ipsum, aliquam neque delectus quas itaque.',
      string: 'src="../image/books/27.jpg"', 
   },
   {
      id: 28, 
      title: 'Детство', 
      author: 'Максим Горький',
      description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ex aspernatur inventore, enim accusantium a reprehenderit veritatis sint numquam necessitatibus expedita debitis. Beatae laboriosam officiis ipsum, aliquam neque delectus quas itaque.',
      string: 'src="../image/books/28.jpg"', 
   },
   {
      id: 29, 
      title: 'Борьба русского народа с немецкими интервентами в XII-XV вв.', 
      author: '',
      description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ex aspernatur inventore, enim accusantium a reprehenderit veritatis sint numquam necessitatibus expedita debitis. Beatae laboriosam officiis ipsum, aliquam neque delectus quas itaque.',
      string: 'src="../image/books/29.jpg"', 
   },
   {
      id: 30, 
      title: 'Капитанская дочка', 
      author: 'Александр Сергеевич Пушкин',
      description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ex aspernatur inventore, enim accusantium a reprehenderit veritatis sint numquam necessitatibus expedita debitis. Beatae laboriosam officiis ipsum, aliquam neque delectus quas itaque.',
      string: 'src="../image/books/30.jpg"', 
   },
   {
      id: 31, 
      title: 'Хаджи-Мурат', 
      author: 'Лев Николаевич Толстой',
      description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ex aspernatur inventore, enim accusantium a reprehenderit veritatis sint numquam necessitatibus expedita debitis. Beatae laboriosam officiis ipsum, aliquam neque delectus quas itaque.',
      string: 'src="../image/books/31.jpg"', 
   },
   {
      id: 32, 
      title: 'Беглец', 
      author: 'Антон Павлович Чехов',
      description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ex aspernatur inventore, enim accusantium a reprehenderit veritatis sint numquam necessitatibus expedita debitis. Beatae laboriosam officiis ipsum, aliquam neque delectus quas itaque.',
      string: 'src="../image/books/32.jpg"', 
   },
   {
      id: 33, 
      title: '', 
      author: 'Тютчев',
      description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ex aspernatur inventore, enim accusantium a reprehenderit veritatis sint numquam necessitatibus expedita debitis. Beatae laboriosam officiis ipsum, aliquam neque delectus quas itaque.',
      string: 'src="../image/books/33.jpg"', 
   },
   {
      id: 34, 
      title: '', 
      author: 'Тютчев',
      description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ex aspernatur inventore, enim accusantium a reprehenderit veritatis sint numquam necessitatibus expedita debitis. Beatae laboriosam officiis ipsum, aliquam neque delectus quas itaque.',
      string: 'src="../image/books/34.jpg"', 
   },
];