const cardsFilmsData = [
    {   
        id: 1,
        title: 'ssssssss',
        yearOfCreate: '1946',
        description: 'Lorem hfkdshflahlfa',
    },
    {   
        id: 2,
        title: 'дофига заголовок',
        yearOfCreate: '1946',
        description: 'description',
    },
    {   
        id: 3,
        title: 'title',
        yearOfCreate: '1946',
        description: 'description',
    },
    {   
        id: 4,
        title: 'title',
        yearOfCreate: '1946',
        description: 'description',
    },
    {   
        id: 5,
        title: 'title',
        yearOfCreate: '1946',
        description: 'description',
    },
    {   
        id: 6,
        title: 'title',
        yearOfCreate: '1946',
        description: 'description',
    },
    {   
        id: 7,
        title: 'title',
        yearOfCreate: '1946',
        description: 'description',
    },
    {   
        id: 8,
        title: 'title',
        yearOfCreate: '1946',
        description: 'description',
    },
    {   
        id: 9,
        title: 'title',
        yearOfCreate: '1946',
        description: 'description',
    },
    {   
        id: 10,
        title: 'title',
        yearOfCreate: '1946',
        description: 'description',
    },
    {   
        id: 11,
        title: 'title',
        yearOfCreate: '1946',
        description: 'description',
    },
    {   
        id: 12,
        title: 'title',
        yearOfCreate: '1946',
        description: 'description',
    },
    {  
        id: 13,
        title: 'title',
        yearOfCreate: '1946',
        description: 'description',
    },
    {   
        id: 14,
        title: 'title',
        yearOfCreate: '1946',
        description: 'description',
    },
    {   
        id: 15,
        title: 'title',
        yearOfCreate: '1946',
        description: 'description',
    },
    {   
        id: 16,
        title: 'title',
        yearOfCreate: '1946',
        description: 'description',
    },
    {   
        id: 17,
        title: 'title',
        yearOfCreate: '1946',
        description: 'description',
    },
    {   
        id: 18,
        title: 'title',
        yearOfCreate: '1946',
        description: 'description',
    },
    {   
        id: 19,
        title: 'title',
        yearOfCreate: '1946',
        description: 'description',
    },
    {   
        id: 20,
        title: 'title',
        yearOfCreate: '1946',
        description: 'description',
    },
    {   
        id: 21,
        title: 'title',
        yearOfCreate: '1946',
        description: 'description',
    },
    {   
        id: 22,
        title: 'title',
        yearOfCreate: '1946',
        description: 'description',
    },
    {   
        id: 23,
        title: 'title',
        yearOfCreate: '1946',
        description: 'description',
    },
    {   
        id: 24,
        title: 'title',
        yearOfCreate: '1946',
        description: 'description',
    },
];