const cardsFilmsData = [
    {   
        id: 1,
        title: 'ssssssss',
        yearOfCreate: '1946',
        description: 'Lorem hfkdshflahlfa',
        string: 'src="../video/1.mp4"',
    },
    {   
        id: 2,
        title: 'дофига заголовок',
        yearOfCreate: '1946',
        description: 'description',
        string: 'src="../video/2.mp4"',
    },
    {   
        id: 3,
        title: 'title',
        yearOfCreate: '1946',
        description: 'description',
        string: 'src="../video/3.mp4"',
    },
    {   
        id: 4,
        title: 'title',
        yearOfCreate: '1946',
        description: 'description',
        string: 'src="../video/4.mp4"',
    },
    {   
        id: 5,
        title: 'title',
        yearOfCreate: '1946',
        description: 'description',
        string: 'src="../video/5.mp4"',
    },
    {   
        id: 6,
        title: 'title',
        yearOfCreate: '1946',
        description: 'description',
        string: 'src="../video/6.mp4"',
    },
    {   
        id: 7,
        title: 'title',
        yearOfCreate: '1946',
        description: 'description',
        string: 'src="../video/7.mp4"',
    },
    {   
        id: 8,
        title: 'title',
        yearOfCreate: '1946',
        description: 'description',
        string: 'src="../video/8.mp4"',
    },
    {   
        id: 9,
        title: 'title',
        yearOfCreate: '1946',
        description: 'description',
        string: 'src="../video/9.mp4"',
    },
    {   
        id: 10,
        title: 'title',
        yearOfCreate: '1946',
        description: 'description',
        string: 'src="../video/10.mp4"',
    },
    {   
        id: 11,
        title: 'title',
        yearOfCreate: '1946',
        description: 'description',
        string: 'src="../video/11.mp4"',
    },
    {   
        id: 12,
        title: 'title',
        yearOfCreate: '1946',
        description: 'description',
        string: 'src="../video/12.mp4"',
    },
    {  
        id: 13,
        title: 'title',
        yearOfCreate: '1946',
        description: 'description',
        string: 'src="../video/13.mp4"',
    },
    {   
        id: 14,
        title: 'title',
        yearOfCreate: '1946',
        description: 'description',
        string: 'src="../video/14.mp4"',
    },
    {   
        id: 15,
        title: 'title',
        yearOfCreate: '1946',
        description: 'description',
        string: 'src="../video/15.mp4"',
    },
    {   
        id: 16,
        title: 'title',
        yearOfCreate: '1946',
        description: 'description',
        string: 'src="../video/16.mp4"',
    },
    {   
        id: 17,
        title: 'title',
        yearOfCreate: '1946',
        description: 'description',
        string: 'src="../video/17.mp4"',
    },
    {   
        id: 18,
        title: 'title',
        yearOfCreate: '1946',
        description: 'description',
        string: 'src="../video/18.mp4"',
    },
    {   
        id: 19,
        title: 'title',
        yearOfCreate: '1946',
        description: 'description',
        string: 'src="../video/19.mp4"',
    },
    {   
        id: 20,
        title: 'title',
        yearOfCreate: '1946',
        description: 'description',
        string: 'src="../video/20.mp4"',
    },
    {   
        id: 21,
        title: 'title',
        yearOfCreate: '1946',
        description: 'description',
        string: 'src="../video/21.mp4"',
    },
    {   
        id: 22,
        title: 'title',
        yearOfCreate: '1946',
        description: 'description',
        string: 'src="../video/22.mp4"',
    },
    {   
        id: 23,
        title: 'title',
        yearOfCreate: '1946',
        description: 'description',
        string: 'src="../video/23.mp4"',
    },
    {   
        id: 24,
        title: 'title',
        yearOfCreate: '1946',
        description: 'description',
        string: 'src="../video/24.mp4"',
    },
];